Genomeviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^genomebrowser/', include('genomebrowser.urls')),
    url(r'^trackhubs/', include('trackhubs.urls'))

]

genomebrowser/urls.py
from django.conf.urls import url
from . import views

app_name = 'genomebrowser'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^(?P<genome_id>[0-9]+)/$', views.detail, name='detail'),

    url(r'^genome_form/$', views.genome_form, name='genome_form'),

    url(r'^(?P<genome_id>[0-9]+)/delete_genome/$', views.delete_genome,
        name='delete_genome'),

]

trackhubs/urls.py
from django.conf.urls import url
from . import views

app_name = 'trackhubs'

urlpatterns = [

    url(r'^$', views.index, name='index'),

    url(r'^(?P<trackhub_id>[0-9]+)/$', views.detail, name='detail'),

    url(r'^create_trackhub/$', views.create_trackhub, name='create_trackhub'),

    url(r'^(?P<trackhub_id>[0-9]+)/create_track/$', views.create_track, name='create_track'),

    url(r'^(?P<trackhub_id>[0-9]+)/delete_trackhub/$', views.delete_trackhub, name='delete_trackhub'),

    url(r'^(?P<trackhub_id>[0-9]+)/delete_track/(?P<track_id>[0-9]+)/$', views.delete_track, name='delete_track'),

]

genomebrowser/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
class Genome(models.Model):
    speciesName = models.CharField(max_length=50)
    taxon = models.CharField(max_length=50)
    auth = models.CharField(max_length=50)
    version = models.CharField(max_length=50)
    ucscName = models.CharField(max_length=50)
    twoBitURI = models.CharField(max_length=500)
    chainSet = models.CharField(max_length=500)
    genes = models.CharField(max_length=500)
    genesDescription = models.CharField(max_length=500)
    genesURI = models.CharField(max_length=500)
    stylesheetURI = models.CharField(max_length=500, default = 'www.biodalliance.org/stylesheets/gencode.xml')
    trixURI = models.CharField(max_length=500)
    collapseSuperGroups = models.BooleanField('True')


    def get_absolute_url(self):
        return reverse('genomebrowser:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.speciesName

trackhubs/models.py
from django.db import models
from genomebrowser.models import Genome

# Create your models here.
class TrackHub(models.Model):
    Genome = models.ForeignKey(Genome, on_delete=models.CASCADE)
    hub_name = models.CharField(max_length=500)
    short_label = models.CharField(max_length=500)
    long_label = models.CharField(max_length=1000)
    email = models.CharField(max_length=500)

    def __str__(self):
        return self.hub_name


class SuperTrack(models.Model):
    TrackHub = models.ForeignKey(TrackHub, on_delete=models.CASCADE)
    name = models.CharField(max_length=500)
    short_label = models.CharField(max_length=500)
    long_label = models.CharField(max_length=1000)

    def __str__(self):
        return self.name


class Track(models.Model):
    TrackHub = models.ForeignKey(TrackHub, on_delete=models.CASCADE)
    Supertrack = models.BooleanField(False)
    name = models.CharField(max_length=500)
    short_label = models.CharField(max_length=500)
    long_label = models.CharField(max_length=1000)
    url = models.CharField(max_length=500)
    track_type = models.CharField(max_length=20)
    color = models.CharField(max_length=500, default='0,0,220')


    def __str__(self):
        return self.name

genomebrowser/forms.py
from django import forms

from .models import Genome


class GenomeForm(forms.ModelForm):

    class Meta:
        model = Genome
        fields = ['speciesName', 'taxon', 'auth', 'version', 'ucscName', 'twoBitURI', 'chainSet',
                  'genes', 'genesDescription', 'genesURI', 'stylesheetURI', 'trixURI', 'collapseSuperGroups']

trackhubs/forms.py
from django import forms
from .models import TrackHub, Track


class TrackHubForm(forms.ModelForm):

    class Meta:
        model = TrackHub
        fields = ['Genome', 'hub_name', 'long_label', 'short_label', 'email']


class TrackForm(forms.ModelForm):

    # Provide an association between the ModelForm and a model
    class Meta:
        model = Track
        fields = ['TrackHub', 'Supertrack', 'name', 'long_label', 'short_label', 'url', 'track_type', 'color']

genomebrowser/views.py
from django.shortcuts import render, get_object_or_404
from .models import Genome
from .forms import GenomeForm
# Create your views here. they are functions, user request something and you give something back.


def genome_form(request):
    form = GenomeForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        genome = form.save(commit=False)
        genome.save()
        return render(request, 'genomebrowser/index.html', {'genome': genome})
    return render(request, 'genomebrowser/genome_form.html', {'form': form})


def delete_genome(request, genome_id):
    genome = Genome.objects.get(id=genome_id)
    genome.delete()
    return render(request, 'genomebrowser/index.html', {'genome': genome})


def detail(request, genome_id):
    genome = get_object_or_404(Genome, pk=genome_id)
    return render(request, 'genomebrowser/detail.html', {'genome': genome})


def index(request):
    genomes = Genome.objects.all()
    return render(request, 'genomebrowser/index.html', {'genomes': genomes})

trackhubs/views.py
from django.shortcuts import render, get_object_or_404
from .forms import TrackHubForm, TrackForm
from .models import TrackHub, Track
import os, shutil
# Create your views here.


def create_trackhub(request):
    form = TrackHubForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        #save the input of the form
        trackhub = form.save(commit=False)
        trackhub.save()
        if not os.path.isdir(os.path.join(trackhub.hub_name)):
            #generate track hub directory
            os.makedirs(os.path.join(trackhub.hub_name))
            hub = open(os.path.join(trackhub.hub_name, 'hub.txt'), 'w')
            hub.write(makehubfile(trackhub))
            hub.close()
            genomes = open(os.path.join(trackhub.hub_name,'genomes.txt'), 'w')
            genomes.write(makegenomesfile(trackhub))
            genomes.close()
        return render(request, 'trackhubs/detail.html', {'trackhub': trackhub})
    return render(request, 'trackhubs/create_trackhub.html', {'form': form})


def index(request):
    trackhubs = TrackHub.objects.all()
    return render(request, 'trackhubs/index.html', {'trackhubs': trackhubs})


def detail(request, trackhub_id):
    trackhub = get_object_or_404(TrackHub, pk=trackhub_id)
    return render(request, 'trackhubs/detail.html', {'trackhub': trackhub})


def create_track(request, trackhub_id):
    form = TrackForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        track = form.save(commit=False)
        track.save()
        trackhub = TrackHub.objects.get(pk=trackhub_id)
        maketrackDbfile(trackhub)
        return render(request, 'trackhubs/detail.html', {'trackhub': trackhub})
    return render(request, 'trackhubs/create_track.html', {'form': form})


def delete_trackhub(request,trackhub_id):
    trackhub = TrackHub.objects.get(pk=trackhub_id)
    #how can I ask for confirmation before deletion??
    trackhub.delete()
    if os.path.isdir(os.path.join(trackhub.hub_name)):
        shutil.rmtree(trackhub.hub_name)
    return render(request, 'trackhubs/index.html', {'trackhub': trackhub})


def delete_track(request,track_id, trackhub_id):
    trackhub = get_object_or_404(TrackHub, pk=trackhub_id)
    track = Track.objects.get(pk=track_id)
    track.delete()
    maketrackDbfile(trackhub)
    return render(request, 'trackhubs/detail.html', {'trackhub': trackhub})


def makehubfile(trackhub):
    return ("hub "+trackhub.hub_name+"\nshortLabel "+trackhub.short_label+"\nlongLabel "+trackhub.long_label +
            "\nemail "+trackhub.email)


def makegenomesfile(trackhub):
    return ("genome "+trackhub.Genome.ucscName+"\ntrackDb "+trackhub.Genome.ucscName+"/trackDb")


def maketrackDbfile(th):
    path = str(th.hub_name) + '/' + str(th.Genome.ucscName)
    if not os.path.isdir(os.path.join(path)):
        os.makedirs(os.path.join(th.hub_name, th.Genome.ucscName))
    trackDb = open(os.path.join(path, 'trackDb.txt'), 'w')
    s = ''
    for track in th.track_set.all():
        s += ("track "+track.name+"\nshortLabel "+track.short_label+"\nlongLabel "+track.long_label+
        '\ntype '+track.track_type+"\nbigDataUrl "+track.url+"\n\n")
    trackDb.write(s)
    trackDb.close()

genomebrowser/templates/genomebrowser/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}GenomeViewer{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'genomebrowser/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Marvel" rel="stylesheet" type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
       <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-targer="#topNavBar">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="{% url 'genomebrowser:index' %}" >GenomeViewer</a>
       </div>


        <!--Items -->

        <div class="collapse navbar-collapse" id="#topNavBar">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Genomes<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    {% block dropdown %}
                    {% endblock %}
                </ul>
                 </li>
                <li class="">
                    <a href="{% url 'genomebrowser:index' %}">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&nbsp;Genomes
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'genomebrowser:genome_form' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Genome
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'trackhubs:index' %}">
                        <span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span>&nbsp;Track Hubs
                    </a>
                </li>
            </ul>

        </div>
    </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

genomebrowser/templates/genomebrowser/detail.html
{% extends 'genomebrowser/base.html' %}
{% block title %}{{ rg }}{% endblock %}
{% block dropdown %}
    {% for genome in genomes %}
      <li><a href="{% url 'genomebrowser:detail' genome.id %}">{{genome.speciesName}}{{genome.ucscName}}</a></li>
    {% endfor %}
{% endblock %}
{% block body %}
{% if error_message %}
    <p><strong> {{ error_message }}</strong></p>
{% endif %}

<script language="javascript" src="http://www.biodalliance.org/release-0.13/dalliance-compiled.js"></script>
<script language="javascript">

var a =  new Browser({
    noPersist:  true,
    chr:          '1',
    viewStart:    32000000,
    viewEnd:      32030000,

    coordSystem: {
      speciesName: '{{ genome.speciesName }}',
      taxon: {{ genome.taxon }} ,
      auth: '{{ genome.auth }}',
      version: '{{ genome.version }}',
	  ucscName: '{{ genome.ucscname }}',
    },

 	 chains: {
	    mm9ToMm10: new Chainset('http://www.derkholm.net:8080/das/mm9ToMm10/', 'NCBIM37', 'GRCm38',
	                             {
	                               speciesName: '{{ genome.speciesName }}',
  	                                taxon: {{ genome.taxon }},
  	                                auth: 'NCBIM',
  	                                version: 37,
  	                                ucscName: 'mm9'
  	                             })
 	   },



    sources:
	 [
			{name:                'Reference Genome',
			 twoBitURI:           '{{ genome.twoBitURI }}',
			 tier_type:           'sequence',
			},

			{name:                 '{{ genome.genes }}',
			 desc:                 '{{ genome.genesDescription }}',
			 uri:                  '{{ genome.genesURI }}',
			 collapseSuperGroups:  true,
			 stylesheetURI:        '{{ genome.stylesheetURI }}',
			 trixURI:              '{{ genome.trixURI }}',
			 provides_karyotype:   true,
			 provides_search:      true
			},

			 {name:                'Repeats',
			 uri:                  'http://www.derkholm.net:8080/das/hsa_54_36p/',
			 stylesheet_uri:       'http://www.derkholm.net/dalliance-test/stylesheets/ens-repeats.xml'
			},

			 {name:                'MeDIP raw',
			 uri:                  'http://www.derkholm.net:8080/das/medipseq_reads'
			},
	 ],

    uiPrefix: 	'//www.biodalliance.org/release-0.13/',





    hubs:
	 [

	 ],

});
</script>

<div id="svgHolder" style='margin-left: 5%; margin-right: 5%; border-width: 1px; border-style: solid; border-color: #ccc; border-radius: 4px; padding: 10px'></div>


{% endblock %}

genomebrowser/templates/genomebrowser/form-template.html
{% for field in form  %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

genomebrowser/templates/genomebrowser/genome_form.html
{% extends 'genomebrowser/base.html' %}
{% block title %}Add new Genome{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Genome</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <form class="form-horizontal" action=" " method="post" enctype="multipart/form-data">
                        {% csrf_token%}
                        {% include 'genomebrowser/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is Genomebrowser?</h3>
                    <p>... </p>
                    <h3>What is ...?</h3>
                    <p>....</p>
                    <h3>What else</h3>
                    <ul>
                        <li>...</li>
                        <li>use 2bit format</li>
                        <li>use Illumina Syntax</li>
                        <li>////</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

genomebrowser/templates/genomebrowser/index.html
{% extends 'genomebrowser/base.html' %}
{% block title %}GenomeViewer{% endblock %}
{% block dropdown %}
    {% for genome in genomes %}
      <li><a href="{% url 'genomebrowser:detail' genome.id %}">{{genome.speciesName}}  {{genome.ucscName}}</a></li>
    {% endfor %}
{% endblock %}
{% block body %}
<script language="javascript" src="http://www.biodalliance.org/release-0.13/dalliance-compiled.js"></script>
<script language="javascript">

var a =  new Browser({
    noPersist:  true,
    chr:          '6 ',
    viewStart:    32000000,
    viewEnd:      32030000,
    cookieKey:    'mouse38',

    coordSystem: {
      speciesName: 'Mus musculus',
      taxon: 10090,
      auth: 'GRCm',
      version: '38',
        //ucsc name: display track hubs
      ucscName: 'mm10',
    },

    chains: { mm9ToMm10: new Chainset('http://www.derkholm.net:8080/das/mm9ToMm10/', 'NCBIM37', 'GRCm38',
                                     {
                                       speciesName: 'Mouse',
                                        taxon: 10090,
                                        auth: 'NCBIM',
                                        version: 37,
                                        ucscName: 'mm9'
                                     })
           },

    sources:
         [
                        {name:                'Reference Genome',
                         twoBitURI:           '//www.biodalliance.org/datasets/GRCm38/mm10.2bit',
                         tier_type:           'sequence',
                        },

                         {name:                'Genes',
                         desc:                 'Gene structures from GENCODE M2',
                         bwgURI:               '//www.biodalliance.org/datasets/GRCm38/gencodeM2.bb',
                         stylesheet_uri:       '//www.biodalliance.org/stylesheets/gencode.xml',
                         trixURI:              '//www.biodalliance.org/datasets/GRCm38/gencodeM2.ix',
                         collapseSuperGroups:  true,
                        },
                        //{name:                 'Genes ENSEMBL',
                        //desc:                  'Gene structures from Ensembl  GRCm38 release 81',
                        //bwgURI:                'biodalltest/musMusGRCm38/mmgenes.bb',
                        //stylesheet_uri:        '//www.biodalliance.org/stylesheets/gencode.xml',
                        //trixURI:               'biodalltest/musMusGRCm38/gencode.ix',
                        //collapseSuperGroups:    true,
                        //},


                       {name:                  'Repeats',
                        uri:                  'http://www.derkholm.net:8080/das/hsa_54_36p/',
                        stylesheet_uri:       'http://www.derkholm.net/dalliance-test/stylesheets/ens-repeats.xml',
                       },

                       {name:                'MeDIP raw',
                       uri:                  'http://www.derkholm.net:8080/das/medipseq_reads'
                      },

                       // {name:                 'T7Aligned',
                       // bamURI:                'T7Aligned.sortedByCoord.out.bam',
                       // baiURI:                'T7Aligned.sortedByCoord.out.bam.bai',
                       //},

                       //{name:       'T12Aligned',
                       // bamURI:      'T12Aligned.sortedByCoord.out.bam',
                       // baiURI:      'T12Aligned.sortedByCoord.out.bam.bai',
                       // },
         ],

    uiPrefix:   '//www.biodalliance.org/release-0.13/',

    hubs:
         [
                //      'http://www.biodalliance.org/datasets/testhub/hub.txt',
                        'http://www.broadinstitute.org/compbio1/PhyloCSFtracks/trackHub/hub.txt',
                //      'http://apprisws.bioinfo.cnio.es/trackHub/hub.txt',
                //      'http://ftp.ebi.ac.uk/pub/databases/blueprint/releases/current_release/homo_sapiens/hub/hub.txt',
                //      'http://ngs.sanger.ac.uk/production/ensembl/regulation/hub.txt',
                //      'http://fantom.gsc.riken.jp/5/datahub/hub.txt'
         ]

});
</script>

<div id="svgHolder" style='margin-left: 5%; margin-right: 5%; border-width: 1px; border-style: solid; border-color:
    #ccc; border-radius: 4px; padding: 10px'></div>

<br>
<br>
<div class="container-fluid" style='margin-left: 5%; margin-right: 5%; border-width: 1px; border-style: solid;
    border-color: #ccc; border-radius: 4px; padding: 10px'>
        <!--genomes-->
        <div class="row">
            <div class="col-sm-12">
                <h4>    Customized Genomes </h4>
            </div>

            {% if genomes %}
                {% for i in genomes %}

                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'genomebrowser:detail' i.pk %}"></a>
                        <div class="caption">
                            <h4>{{ i.speciesName }} {{ i.ucscName }} </h4>
                            <h5>{{ i.ucscName }}</h5>

                            <!-- View Details -->
                            <a href="{% url 'genomebrowser:detail' i.id %}" class="btn btn-primary btn-sm" role="button">View Browser</a>

                            <!-- Update Genome -->
                            <form action="" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="genome_id" value="{{ i.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-edit"></span>
                                     </button>
                            </form>

                            <!-- Delete Genome -->
                            <form action="{% url 'genomebrowser:delete_genome' i.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="genome_id" value="{{ i.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                     </button>
                            </form>
                        </div>
                    </div>
                </div>
                {% endfor %}
             {% endif %}
        </div>

    </div>
{% endblock %}

trackhubs/templates/trackhubs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}GenomeViewer{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'genomebrowser/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Marvel" rel="stylesheet" type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
       <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-targer="#topNavBar">
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="{% url 'trackhubs:index' %}" >GenomeViewer</a>
       </div>


        <!--Items -->
        <div class="collapse navbar-collapse" id="#topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'trackhubs:index' %}">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>&nbsp;Trackhubs
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'trackhubs:create_trackhub' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Trackhub
                    </a>
                </li>
                  <li class="">
                      <a href="{% url 'genomebrowser:index'%}">
                      <span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span>&nbsp;Genomes
                  </a>

            </ul>

        </div>
    </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

trackhubs/templates/trackhubs/detail.html
{% extends 'trackhubs/base.html' %}
{% block title %}{{ trackhub.hub_name }}{% endblock %}
{% block body %}
{% if error_message %}
    <p><strong> {{ error_message }}</strong></p>
{% endif %}

<div class="container">
  <h4 style="color:#8A8A8A">Track Hub</h4><h4>{{ trackhub.hub_name }}</h4>
  <p>   {{ trackhub.short_label }}</p>

  <div class="panel-group">
      {% for track in trackhub.track_set.all %}
    <div class="panel panel-default">
      <div class="panel-heading">{{ track.name }}</div>
      <div class="panel-body">
          {{ track.short_label }}<br>
          {{ track.long_label }}<br>
          {{track.url }}<br><br>
                            <!-- Update Track -->
                            <form action="" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="track_id" value="{{ track.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-edit"></span>
                                     </button>
                            </form>
                            <!-- Delete Track -->
                            <form action="{% url 'trackhubs:delete_track' trackhub.id track.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="track_id" value="{{ track.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                     </button>
                            </form>
      </div>
    </div>
       {% endfor %}

      <ul class="nav nav-pills" style="margin-left: 5px;">
                <li role="presentation"><a href="{% url 'trackhubs:create_track' trackhub.id %}">Add New Track</a></li>
   </ul>
  </div>
</div>

{% endblock %}

trackhubs/templates/trackhubs/form-template.html
{% for field in form  %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

trackhubs/templates/trackhubs/index.html
{% extends 'trackhubs/base.html' %}
{% block title %}Trackhubs{% endblock %}

{% block body %}

{% if error_message %}
    <p><strong> {{ error_message }}</strong></p>
{% endif %}

<div class="container">
  <h3>Track Hubs </h3>
  <p>   create your own Track Hub </p>

  <div class="panel-group">
      {% for t in trackhubs %}
    <div class="panel panel-default">
      <div class="panel-heading">{{ t.hub_name }}</div>
      <div class="panel-body">
          {{ t.short_label }}<br>
          {{ t.long_label }}<br><br>
                            <!-- View Details -->
                            <a href="{% url 'trackhubs:detail' t.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Get URL -->
                            <a href="" class="btn btn-primary btn-sm" role="button">Get URL</a>

                            <!-- Update Trackhub -->
                            <form action="" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="trackhub_id" value="{{ t.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-edit"></span>
                                     </button>
                            </form>
                            <!-- Delete Trackhub -->
                            <form action="{%  url 'trackhubs:delete_trackhub' t.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="trackhub_id" value="{{ t.id }}" />
                                     <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                     </button>
                            </form>
      </div>
    </div>
       {% endfor %}

      <ul class="nav nav-pills" style="margin-left: 5px;">
                <li role="presentation"><a href="{% url 'trackhubs:create_trackhub' %}">Add New Trackhub</a></li>
   </ul>
  </div>
</div>

{% endblock %}